<a href="https://colab.research.google.com/github/SalmaSherif7070/Neural-Network-from-scratch-/blob/main/A4_%7C_ML_%7C_NN_from_scratch_%7C_Salma_Sherif_2022200622.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from keras.datasets import mnist
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape((x_train.shape[0], -1)) / 255.
x_test = x_test.reshape((x_test.shape[0], -1)) /255.

y_train = np.eye(10)[y_train]
y_test = np.eye(10)[y_test]

In [ ]:
# random weights
w1 = np.random.randn(784, 64)
w2= np.random.randn(64, 10)
# w_b1 = np.random.randn(1, 64)
# w_b2 = np.random.randn(1, 10)

w_b1 = np.ones((1, 64))
w_b2 = np.ones((1, 10))
def sigmoid(z):
    s = 1. / (1. + np.exp(-z))
    return s

In [ ]:
b = 1.0
LR =  0.01
for j in range (20):
  for i in range (len(x_train)):
    # Forward
    netj_1 = np.dot(x_train[i].T, w1) + w_b1 * b
    activation1 = sigmoid(netj_1)
    netj_2 = np.dot(activation1, w2) + w_b2 * b
    activation2 = sigmoid(netj_2)
    # print(activation1)

    # loss fun
    array_ones = np.ones(activation2.shape)
    o_error =  (y_train[i] - activation2)
    sigma_2 = (activation2* (array_ones-activation2)) * o_error
    Delata_2 =  np.dot(netj_1.T, sigma_2) * LR
    w2 = w2 + Delata_2
    # print(w2)

    array_ones = np.ones(activation1.shape)
    h_error = np.dot(sigma_2, w2.T)
    sigma_1 = (activation1*(array_ones-activation1))* h_error
    Delata_1 =  np.dot(x_train[i].reshape(-1, 1), sigma_1) *  LR
    w1 = w1 + Delata_1


    w_b2 += LR * sigma_2 * b
    w_b1 += LR * sigma_1 * b

  print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
netj_1 = np.dot(x_test, w1) + w_b1
activation1 = sigmoid(netj_1)
netj_2 = np.dot(activation1, w2) + w_b2
activation2 = sigmoid(netj_2)

In [ ]:
predictions = np.argmax(activation2, axis = 1)
y_test_labels = np.argmax(y_test, axis = 1)
accuracy = np.mean(predictions == y_test_labels)
print(f"Accuracy = {accuracy*100} %")

Accuracy = 90.49000000000001 %


In [ ]:
conf_matrix = confusion_matrix(y_test_labels, predictions)
print("Confusion Matrix: ", conf_matrix)

Confusion Matrix:  [[ 960    0    3    0    1    1    9    1    4    1]
 [   0 1118    3    4    1    0    4    1    3    1]
 [  12    3  903   18   15    3   12   15   40   11]
 [  10    4   21  893    1   28    5   13   26    9]
 [   4    6    7    3  886    1   20    5   11   39]
 [  18    2    4   32   19  715   22   17   55    8]
 [  15    4   12    3    8   15  889    2   10    0]
 [   3   14   24    5   10    2    0  932    4   34]
 [  11    7    7   20   14   12   10    9  866   18]
 [   7    7    1    9   42   15    2   18   21  887]]
